// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG5CrepkaZDr0MBa0OcUozgGg1TzT74ls',
    appId: '1:709314752684:web:5263d099da2789fe74af09',
    messagingSenderId: '709314752684',
    projectId: 'financeapp-ead7f',
    authDomain: 'financeapp-ead7f.firebaseapp.com',
    storageBucket: 'financeapp-ead7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtEgB2SC5OTl-OmKBK1A54JcoJcgrK1_U',
    appId: '1:709314752684:android:14fe5174d0f7393b74af09',
    messagingSenderId: '709314752684',
    projectId: 'financeapp-ead7f',
    storageBucket: 'financeapp-ead7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4YA2nC9sPyQsVdlOzYohl17UNA4OyLbI',
    appId: '1:709314752684:ios:954f8bff6caa995174af09',
    messagingSenderId: '709314752684',
    projectId: 'financeapp-ead7f',
    storageBucket: 'financeapp-ead7f.appspot.com',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4YA2nC9sPyQsVdlOzYohl17UNA4OyLbI',
    appId: '1:709314752684:ios:c4b5fd6f0bc8349274af09',
    messagingSenderId: '709314752684',
    projectId: 'financeapp-ead7f',
    storageBucket: 'financeapp-ead7f.appspot.com',
    iosBundleId: 'com.example.financeApp.RunnerTests',
  );
}
